// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6p5h-hBjwjgGdFspkFmXIrauXH1z1RC8',
    appId: '1:415751455004:web:3e902f9bbc8dafd38dfad9',
    messagingSenderId: '415751455004',
    projectId: 'twogetherapp-65678',
    authDomain: 'twogetherapp-65678.firebaseapp.com',
    storageBucket: 'twogetherapp-65678.firebasestorage.app',
    measurementId: 'G-TJWHDSQT3J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt2WIw8PFx6EXeQoLz8weHoYBRv84H5jw',
    appId: '1:415751455004:ios:82ca7a5733ccc93d8dfad9',
    messagingSenderId: '415751455004',
    projectId: 'twogetherapp-65678',
    storageBucket: 'twogetherapp-65678.firebasestorage.app',
    iosBundleId: 'com.twogether.twogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt2WIw8PFx6EXeQoLz8weHoYBRv84H5jw',
    appId: '1:415751455004:ios:82ca7a5733ccc93d8dfad9',
    messagingSenderId: '415751455004',
    projectId: 'twogetherapp-65678',
    storageBucket: 'twogetherapp-65678.firebasestorage.app',
    iosBundleId: 'com.twogether.twogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6p5h-hBjwjgGdFspkFmXIrauXH1z1RC8',
    appId: '1:415751455004:web:1dce51f2cfb005a98dfad9',
    messagingSenderId: '415751455004',
    projectId: 'twogetherapp-65678',
    authDomain: 'twogetherapp-65678.firebaseapp.com',
    storageBucket: 'twogetherapp-65678.firebasestorage.app',
    measurementId: 'G-R7LQT46QMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKOEXJOnFubVsqBdDoLsYen7APH6_FuGA',
    appId: '1:415751455004:android:4dded0f1071a64ed8dfad9',
    messagingSenderId: '415751455004',
    projectId: 'twogetherapp-65678',
    storageBucket: 'twogetherapp-65678.firebasestorage.app',
  );

}